export const DEFAULT_CONTENT = [
  {pageKey:'v1',sectionKey:'executive',sortOrder:1,title:'Executive Summary',bodyMarkdown:`본 사업은 인도 현지 실행 인프라를 이해하고 한국에서 기업을 발굴할 수 있는 영업 파트너를 선발·양성하는 조직 구축사업이다. 1기 20명은 IBS에서 30일간 체류하며 영업·초기진단에 필요한 표준지식과 현장 감각을 습득한다.\n\n- 1기 교육매출: **4억 원**\n- 1기 계획 잔여: **0원**\n- 인도 법인 설립비: **1기에만 반영**\n- 2기 이후 잉여자금: **구성원 협의로 활용**\n\n> 수료자의 권한은 기업 발굴, 초기상담, 자료요청, 진단양식 작성과 공식 등록으로 제한한다.`},
  {pageKey:'v1',sectionKey:'structure',sortOrder:2,title:'사업 구조와 권한 분리',bodyMarkdown:`## 운영 흐름\n1. 한국 시행사 모집·검증\n2. IBS·본사 현지교육\n3. 수료·활동계약\n4. 한국 기업 발굴\n5. 본사·IBS 실행\n6. 성과형 수수료\n\n| 영역 | 수료자 | 본사·IBS |\n|---|---|---|\n| 법인·공장 | 조건·자료 안내 | 구조·부지·설립·계약 |\n| 인증·특허 | 기존자료 확인 | 분류·출원·등록 |\n| 수출입 | 준비도·기초조건 설명 | 가격·통관·계약·실행 |\n| 부동산 | 요구조건 정리 | IBS 조사·협상·관리 |`},
  {pageKey:'v1',sectionKey:'selection',sortOrder:3,title:'참가자 선발과 파트너 등급',bodyMarkdown:`참가비 지불능력만으로 선발하지 않는다. 기존 고객 인프라, B2B 영업경력, 전문 산업군, 신뢰·윤리, 활동계획과 현지체류 가능성을 평가한다.\n\n- Trainee: 교육 참여·자료 열람\n- Certified Sales Partner: 기업 발굴·초기진단·등록\n- Senior Partner: 제안미팅·산업 프로젝트 리드\n- Regional / Industry Lead: 지역·산업 파트너 관리\n- Suspended: 신규 영업·브랜드·보호정보 제한`},
  {pageKey:'v1',sectionKey:'basic-course',sortOrder:4,title:'IBS 1개월 기본과정',bodyMarkdown:`| 주차 | 교육내용 | 산출물 |\n|---|---|---|\n| 1주 | 문화·지역·힌디어·상담 질문법 | 인도진출 1차 진단표 |\n| 2주 | 법인·공장·인증·특허·수출조건 | 기업 체크리스트 |\n| 3주 | 부동산·수출입·IBS 서비스·쇼룸 | 서비스 매핑·제안서 |\n| 4주 | 현장방문·롤플레이·보안·계약·수수료 | 최종평가·영업계획 |\n\n수료증은 교육이수 사실을 증명하고 실제 활동자격은 별도 계약과 실적·윤리·재교육으로 갱신한다.`},
  {pageKey:'v1',sectionKey:'advanced-course',sortOrder:5,title:'IBS 거주형 고급과정',bodyMarkdown:`기본과정 우수 수료자 또는 동등한 경험자 중 현지 체류·문서·언어·프로젝트 역량을 확인한 인원을 **3~6개월 거주형**으로 선발한다.\n\n1. 정착·보안\n2. 프로젝트 동행\n3. 자료·보고 보조\n4. 감독하 부분업무 담당\n5. 최종 수행평가\n6. 산업·지역별 전문가 등록\n\n법률·세무·가격·계약·관계자 배정은 책임자 승인 후 수행한다.`},
  {pageKey:'v1',sectionKey:'governance',sortOrder:6,title:'조직·법인·거버넌스',bodyMarkdown:`- 이동환: 기획·상품·가격·문서·계약·시스템·PM\n- 협력자: 한국 고객사·영업 인프라·시행사 연결\n- 서용혁: 현지 네트워크·전문가·실행자 검증\n- 문일도: 문화·정치·언어·문서·협상\n- 조혜정/IBS: 센터·숙박·부동산·쇼룸·현지실행\n- 정의학/터메릭: 인적자산·시설·전문가·유통망\n- 권기철/K-BIZ: 참여 확정 시 강의·자문·대외신뢰\n\n인도 법인 예정 구성은 별도 협의하며 협력자의 법인 참여는 자동 전제하지 않는다. 역할보상, 법인지분, IBS 수행수익, 프로젝트 기여수익과 배당을 분리한다.`},
  {pageKey:'v1',sectionKey:'finance',sortOrder:7,title:'1기 재무와 자금원칙',bodyMarkdown:`| 항목 | 금액 |\n|---|---:|\n| 교육 참가비 매출 | 400,000,000원 |\n| 역할보상·강사·시행사 | 225,000,000원 |\n| IBS 숙박 | 88,824,000원 |\n| 항공 | 21,844,800원 |\n| IBS 예비비 | 20,000,000원 |\n| 인도 법인 설립 | 14,331,200원 |\n| IBS 쇼룸 풀 | 30,000,000원 |\n| 최종 잔여 | 0원 |\n\n인도 법인 설립비는 1기에만 반영한다. 권기철 불참, 환율·항공·숙박 절감, 예비비 잔액 등은 구성원 협의재원으로 전환한다.`},
  {pageKey:'v1',sectionKey:'risk',sortOrder:8,title:'리스크 헷지와 실행 게이트',bodyMarkdown:`- 교육범위·수익 비보장·수료증 성격을 계약과 모집문구에 동일 표시\n- VAT·환율·운영진 숙박·비자·보험·차량·법무·회계비 확정\n- 공식채널·프로젝트 ID·직접수금 금지·계정·접속기록 적용\n- 산업·지역 정원과 리드 보호기간으로 과잉경쟁 통제\n- IBS 수용량표와 대체강사·원격모듈·비상일정 운영\n- 계좌분리·2인 승인·증빙·월간 결산 적용\n\n> 주요 계약, 예산, 안전, 개인정보, 계정·감사체계가 확정된 이후 모집금 수납을 개시한다.`},
  {pageKey:'v2',sectionKey:'executive',sortOrder:1,title:'Executive Summary',bodyMarkdown:`1기 20명의 한국 영업 파트너를 선발·양성한 뒤 Indiadesk와 Ctrl Shift Trade에 기업을 등록하고 시장검증·IBS 실행·쇼룸·바이어 발굴·수출입 거래로 전환한다.\n\n- 영업 파트너: 고객과 기업 유입\n- Indiadesk: 멀티피드 콘텐츠와 B2B 검증 데스크\n- 시장검증: 수출 전 가격·패키지·채널 증거 확보\n- IBS: 숙박·부동산·쇼룸·현지 수행\n- Ctrl Shift Trade: 조건매칭·협상·MOQ·계약·정산\n\n1기 교육매출은 영업이익을 남기지 않고 조직·법인·쇼룸·현지기반에 배분한다.`},
  {pageKey:'v2',sectionKey:'funnel',sortOrder:2,title:'Full Funnel 비즈니스 아키텍처',bodyMarkdown:`| 단계 | 조직·플랫폼 활동 | 매출 |\n|---|---|---|\n| 인지 | Indiadesk 피드·프레스·세미나 | 광고·행사 |\n| 파트너 | 선발·IBS 교육·활동계약 | 참가비·재교육 |\n| 기업 유입 | 기업·제품·오더·프로필 등록 | 진단·자문 |\n| 검증 | 현장·소비자·가격·채널 테스트 | 시장검증비 |\n| 실행 | 법인·인증·부동산·쇼룸 | 수행비·관리비 |\n| 거래 | 조건매칭·협상·MOQ·계약 | 성공·거래수수료 |\n| 반복 | 재주문·리테이너·제휴·구독 | 반복수익 |`},
  {pageKey:'v2',sectionKey:'indiadesk',sortOrder:3,title:'Indiadesk 멀티피드 SNS형 플랫폼',bodyMarkdown:`Indiadesk(가칭)는 쇼핑몰이 아니라 **Threads형 텍스트 중심 수출입 피드 + B2B 검증 데스크**다.\n\n- 메인 멀티피드: 정보·아티클·제품·오더·검증·프레스\n- 검색·필터: 산업·지역·방향·MOQ·가격·검증상태\n- 기업·제품 상세: 인증·목표·거래조건·검증상태\n- 오더 작성: 구매·수출 조건, 수량, 예산, 납기\n- 모더레이션: 허위·광고·민감정보·보호정보 승인\n- 번역·문서: 한국어·영어·힌디어와 AI 초안\n- 프로필: 고객·프로젝트·수수료·권한·실적`},
  {pageKey:'v2',sectionKey:'market-validation',sortOrder:4,title:'기업 DB와 시장검증',bodyMarkdown:`영업 파트너는 임의 견적·계약을 체결하지 않고 기업·제품·목표·예산·인증·위험·희망거래를 표준 양식으로 등록한다.\n\n1. 기본진단\n2. 검증설계\n3. 현장조사\n4. 소비자반응\n5. 채널검증\n6. 바이어탐색\n7. 파일럿\n8. 런칭·반복\n\n검증결과가 일정 기준을 통과한 기업만 IBS 실행과 수출입 거래로 전환한다.`},
  {pageKey:'v2',sectionKey:'ibs',sortOrder:5,title:'IBS 실행·쇼룸·고급과정',bodyMarkdown:`IBS는 교육·숙박, 비즈니스센터, 법인·전문가 조정, 공장·사무실·주거 부동산, 쇼룸, 시장검증과 수출입 현지관리를 수행한다.\n\n1기에는 쇼룸 입점지원 풀 **3,000만 원**을 조성하고 업체당 **200만 원**, 최대 15개사를 지원한다. 지원은 현금지급이 아니라 입점·운영서비스 상계방식으로 관리한다.\n\nIBS 거주형 고급과정은 현지 프로젝트의 자료·미팅·샘플·일정·보고를 담당할 실행인력을 양성한다.`},
  {pageKey:'v2',sectionKey:'ctrlshift',sortOrder:6,title:'Ctrl Shift Trade 거래운영체계',bodyMarkdown:`- 산업, 예산, 지역, 거래형태, MOQ, 가격, 마진, 인증, 납기, 위험허용도를 구조화한다.\n- DB가 검색과 스코어링을 수행하고 AI는 매칭이유·다국어 요약·제안·협상 초안을 보조한다.\n- 운영자가 응답, 신뢰, 문서, 일정, 현지실행과 정산을 관리한다.\n- MOQ 미달 수요는 조건이 맞는 복수 바이어를 익명으로 집계한다.\n\n개발은 Sheet·문서 → Indiadesk·CRM → 조건필터 → AI → MOQ·인보이스·정산 → 파트너 API 순으로 진행한다.`},
  {pageKey:'v2',sectionKey:'security',sortOrder:7,title:'관계자 웹·계정·디바이스 정책',bodyMarkdown:`- Cloudflare Pages 정적 UI + Pages Functions API\n- Google Sheets: Accounts, Devices, AccessLogs, Settings, Content, Documents, AuditLogs\n- 비밀번호: PBKDF2-SHA256 해시 검증, 복호화하지 않음\n- 세션: HMAC 서명, HttpOnly·Secure·SameSite 쿠키, CSRF 토큰\n- 게스트: PC 1대 + 모바일 1대\n- 초과정책: BLOCK / REPLACE / ALLOW를 Admin이 계정별 설정\n- 기록: IP, 국가, 도시, Cloudflare colo, 기기, OS, 브라우저, 성공·실패 사유\n- Admin: 기기 제한 없음, 계정·기기·내용·문서·로그 관리`},
  {pageKey:'v2',sectionKey:'finance-risk',sortOrder:8,title:'재무·리스크·확장',bodyMarkdown:`인도 법인 설립비 **14,331,200원**은 1기에만 반영한다. 2기 이후 동일 금액과 환율·항공·강사·예비비 차액은 구성원 협의로 활용한다.\n\n핵심 리스크는 교육 기대, 0원 예산, 계정·문서 유출, Google Sheets 단일저장, 콘텐츠 허위정보, 리드 우회, IBS 과부하, 개인정보 해외이전, AI 오류, MOQ·결제·품질, 구성원 이해상충이다.\n\n2기 진행과 기능개발은 모집인원이 아니라 활동률, 유료전환, 고객만족, 직접거래·환불·정보사고 지표를 통과한 경우에 확정한다.`}
];
